// Import FontAwesome
import { library, dom } from "@fortawesome/fontawesome-svg-core";
import {
  faAlignLeft,
  faAngry,
  faArrowLeft,
  faBatteryThreeQuarters,
  faBell,
  faCalendarAlt,
  faCalendarTimes,
  faCamera,
  faCarSide,
  faCheckCircle,
  faCircle,
  faCog,
  faCogs,
  faComments,
  faDollarSign,
  faEllipsisV,
  faExclamationCircle,
  faExclamationTriangle,
  faFileInvoice,
  faFileInvoiceDollar,
  faFlagUsa,
  faGasPump,
  faGlobeAmericas,
  faHandHoldingUsd,
  faHistory,
  faMapMarkerAlt,
  faMinus,
  faParking,
  faPlus,
  faPowerOff,
  faSearch,
  faShippingFast,
  faSignOutAlt,
  faSpinner,
  faTachometerAlt,
  faTimesCircle,
  faToolbox,
  faUser
} from "@fortawesome/free-solid-svg-icons";

import { faCanadianMapleLeaf } from "@fortawesome/free-brands-svg-icons";

library.add(
  faAlignLeft,
  faAngry,
  faArrowLeft,
  faBatteryThreeQuarters,
  faBell,
  faCalendarAlt,
  faCalendarTimes,
  faCamera,
  faCanadianMapleLeaf,
  faCarSide,
  faCheckCircle,
  faCircle,
  faCog,
  faCogs,
  faComments,
  faDollarSign,
  faEllipsisV,
  faExclamationCircle,
  faExclamationTriangle,
  faFileInvoice,
  faFileInvoiceDollar,
  faFlagUsa,
  faGasPump,
  faGlobeAmericas,
  faHandHoldingUsd,
  faHistory,
  faMapMarkerAlt,
  faMinus,
  faParking,
  faPlus,
  faPowerOff,
  faSearch,
  faShippingFast,
  faSignOutAlt,
  faSpinner,
  faTachometerAlt,
  faTimesCircle,
  faToolbox,
  faUser
);

dom.watch();
